// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqdwrtldizqntvkytmnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZHdydGxkaXpxbnR2a3l0bW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTg0NzEsImV4cCI6MjA2NDMzNDQ3MX0.bcmjYjRGzRARfaGe_FfC4rvysxwZ1ll0zxO5otN2qXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);